name = "readme-so"
compatibility_date = "2024-01-01"

[env.production]
name = "readme-so"

[env.preview]
name = "readme-so-preview"

# KV Namespace binding
[[kv_namespaces]]
binding = "README_STORE"
id = "dbc88d119c6a41f1a6807021a4fff14e"
preview_id = "9456b38ef9f248e88609c3bb8edb85f7"
